name: Java CI/CD with Gradle

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with JUnit
        run: ./gradlew test

      - name: Create distribution package
        run: ./gradlew distZip

      - name: Upload Build Artifacts (JAR files)
        uses: actions/upload-artifact@v4
        with:
          name: jar-files-${{ github.ref_name }}
          path: build/libs/*.jar
          retention-days: 30

      - name: Upload Build Artifacts (distribution)
        uses: actions/upload-artifact@v4
        with:
          name: distribution-zip-${{ github.ref_name }}
          path: build/distributions/*.zip
          retention-days: 30

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ github.ref_name }}
          path: build/reports/tests/test/
          retention-days: 7